variable region {}
variable project_name {}
variable vpc_cidr {}
variable pub_sub_1a_cidr {}
variable pub_sub_2b_cidr {}
variable prv_sub_3a_cidr {}
variable prv_sub_4b_cidr {}
variable prv_sub_5a_cidr {}
variable prv_sub_6b_cidr {}
